PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS projects(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code TEXT UNIQUE,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS vendors(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT
);

CREATE TABLE IF NOT EXISTS rfis(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  externalKey TEXT UNIQUE,
  projectId INTEGER NOT NULL,
  vendorId INTEGER,
  title TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Open',
  createdAt TEXT NOT NULL,
  dueDate TEXT,
  closedAt TEXT,
  priority TEXT,
  assignee TEXT,
  FOREIGN KEY(projectId) REFERENCES projects(id) ON DELETE CASCADE,
  FOREIGN KEY(vendorId) REFERENCES vendors(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS notifications(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  rfiId INTEGER NOT NULL,
  type TEXT NOT NULL,
  message TEXT NOT NULL,
  createdAt TEXT NOT NULL,
  FOREIGN KEY(rfiId) REFERENCES rfis(id) ON DELETE CASCADE
);
